<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Click me</name>
   <tag></tag>
   <elementGuidId>d6313772-18e3-491e-b4d5-e3f6f1e12056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button-container > button.practice-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffd02dec-d409-4d8c-be9f-cd6e32905bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>practice-button</value>
      <webElementGuid>03b5a5a4-8619-4082-8f75-e79b1e30e581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>basic-click</value>
      <webElementGuid>184e4629-dde3-4ffe-898a-79c628cae4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click me</value>
      <webElementGuid>f464c7f1-4a45-4739-905c-3ab0b0d2ef21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;component-container&quot;]/div[@class=&quot;button-container&quot;]/button[@class=&quot;practice-button&quot;]</value>
      <webElementGuid>ccb16dfd-a10f-4dbc-9dcb-02fe88c69522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/button</value>
      <webElementGuid>9bf4a6b9-937e-4119-bf9e-5db0abb3d467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accordion 1'])[1]/following::button[1]</value>
      <webElementGuid>8a23423c-411b-4a17-b0c7-55e601792354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double click me'])[1]/preceding::button[1]</value>
      <webElementGuid>e73511a0-4022-45fc-b3f2-9ff320cc2b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right click me'])[1]/preceding::button[2]</value>
      <webElementGuid>e7d7beaf-2874-4cd3-b19e-1eb144be95b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click me']/parent::*</value>
      <webElementGuid>0e72d7c0-9cb5-41ec-89bf-d82171289ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button</value>
      <webElementGuid>1dc1d15a-56e8-4e50-881b-935643a8c38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Click me' or . = 'Click me')]</value>
      <webElementGuid>7c041429-37b6-4b26-8b95-2eb5e27bf6fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
