<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Accordions</name>
   <tag></tag>
   <elementGuidId>9764285a-9503-4e2c-8ebb-12effb0dfb97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.accordions-container.container-outline > h2.container-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b5a29075-5204-42c8-a496-71024ba44d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container-text</value>
      <webElementGuid>cf0c0343-33fc-49ef-aac1-f177a472bd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accordions</value>
      <webElementGuid>bcd652af-051c-478f-8180-17046b55b360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;accordions-container container-outline&quot;]/h2[@class=&quot;container-text&quot;]</value>
      <webElementGuid>cc64a0bc-0d77-4aad-ac9f-f8e2f4f5a4f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/h2</value>
      <webElementGuid>b3f4323f-fd1b-4f5a-8bf2-514d9aa614cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Links'])[1]/following::h2[1]</value>
      <webElementGuid>fe080f4d-c961-4403-bfaa-86f7ac4474ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Checkboxes'])[1]/following::h2[1]</value>
      <webElementGuid>f74d1cac-b63e-498b-8a52-c7e62c94a678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iframes'])[1]/preceding::h2[1]</value>
      <webElementGuid>ebf92041-2445-4b5a-aaf6-6ca85d95d931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apis'])[1]/preceding::h2[2]</value>
      <webElementGuid>412cfcee-c63e-411c-bc90-d6662b9ff5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accordions']/parent::*</value>
      <webElementGuid>5190d779-eaca-4a47-9c7d-b2fa7fc7bc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h2</value>
      <webElementGuid>4043e477-ff93-4985-8091-b08b4469779b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Accordions' or . = 'Accordions')]</value>
      <webElementGuid>56b83e53-e7e8-43a7-b481-e34d01689ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
